### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by enenH** [ri-char/pwatch#3]
我读了看雪的文章,我在尝试使用register_user_hw_breakpoint时也发生了"触发一次断点后会导致整个线程卡死，直到断点删除"，我看都没人提及，以为是我代码的问题，这个有什么方法解决吗,rwProcMem33也会发生这个情况吗

**Comment by ri-char** [comment]
卡死的原因是触发读写断点后，恢复执行，执行的又是那一行汇编，然后会再次触发断点，导致死循环。rwProcMem33也会有这个情况。

正确的做法是，触发断点、临时删除断点、单步执行、恢复断点、继续运行。但这实现比较复杂，linux内核中只会给perf_event功能有这个逻辑，参考代码[arch/arm64/kernel/hw_breakpoint.c#L657](https://elixir.bootlin.com/linux/v5.15.94/source/arch/arm64/kernel/hw_breakpoint.c#L657)。

我没有找到恨到的解决办法，最简单可行的方法就是直接使用perf_event进行断点，它底层也是register_user_hw_breakpoint。

**Comment by enenH** [comment]
其实我想做到修改寄存器这种功能，还有perf_event能读浮点寄存器吗

**Comment by ri-char** [comment]
可以读 但是不能修改

**Comment by enenH** [comment]
读浮点寄存器要怎么操作呢

**Comment by ri-char** [comment]
好像不太好加，[x86](https://elixir.bootlin.com/linux/latest/source/arch/x86/include/uapi/asm/perf_regs.h)的寄存器头文件里面有浮点数寄存器的定义，加起来比较方便；但是[arm64](https://elixir.bootlin.com/linux/latest/source/arch/arm64/include/uapi/asm/perf_regs.h)里面没有。

**Comment by enenH** [comment]
大佬加油

**Comment by enenH** [comment]
register_user_hw_breakpoint在内核5.10版本以上符号不再导出，有其他代替吗

**Comment by SeeFlowerX** [comment]
自荐一下 https://github.com/SeeFlowerX/stackplz

实现了断点功能，对用户态下断一般不会卡住，内核地址下断大概率会卡，仅支持arm64
