### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by enenH** [ri-char/pwatch#5]
可以用PERF_EVENT_IOC_SET_OUTPUT 将一个进程所有task绑定到一个fd上进行读取事件来节省吗

**Comment by ri-char** [comment]
感谢你的提问！
如果pref_event监听的是所有cpu,那么绑定的事件必须是同一个task，参考源码：
https://github.com/torvalds/linux/blob/1dd28064d4164a4dc9096fd1a7990d2de15f2bb6/kernel/events/core.c#L12304
所以无法实现。
